### PR TITLE
Add templates folder to the build directory

### PR DESCRIPTION
**Pull request by Siegrift**
After testing the deployed services CLI on npx I found out that the CLI doesn't work.
@amarthadan then told me that I can verify the `npx` locally as well (It didn't cross my mind and I only verified the publishing).

Anyway, I've tested this locally using verdaccio now and it works.

### CODE REVIEW

**Comment by Siegrift** [comment]
How to test:

1. Install verdaccio https://verdaccio.org/docs/installation
2. Run verdaccio in console `verdaccio` 
3. Run `npm get registry` and save it (it will be the original npm registry)
4. Run `npm set registry http://localhost:4873/`
5. Create verdaccio user: `npm adduser --registry http://localhost:4873/`
6. Run `yarn publish` from the root of the package
7. Run `npx --package @api3/services --call create-beacon-reader-app`
8. Run `npm set registry https://registry.npmjs.org/`

**Comment by Siegrift** [comment]
Documentation https://github.com/api3dao/api3-docs/pull/590

**Review by amarthadan — APPROVED** [review]
It looks like it's working.

Why is the package named `@api3/services` when the binary name is `create-beacon-reader-app`? Wouldn't it make more sense to call it `api3/create-beacon-reader-app`? Similar to `create-react-app`.

And BTW, you can call just `npx @api3/services` directly without any arguments. It's actually better because you can then pass package arguments directly and they are passed to the package instead of being treated as `npx` arguments.

BTW2, the current package can be installed only on the system with installed git due to the `api3dao` dependencies. I guess that's not really an issue but maybe we can add a warning to the docs.

**Comment by Siegrift** [comment]
> Why is the package named @api3/services when the binary name is create-beacon-reader-app? Wouldn't it make more sense to call it api3/create-beacon-reader-app? Similar to create-react-app.

This is because this repo will also provide an API unrelated to the CLI (e.g. api3 operated beacons). It's also possible that we will create some other CLIs. It might make sense to split the CLI part to a separate package, but we can do that later in needed.

> And BTW, you can call just npx @api3/services directly without any arguments. It's actually better because you can then pass package arguments directly and they are passed to the package instead of being treated as npx arguments.

Yeah, however that way the command looks really vague (you just see @api3/services). This is a bit more explicit so I like it better.

> BTW2, the current package can be installed only on the system with installed git due to the api3dao dependencies. I guess that's not really an issue but maybe we can add a warning to the docs.

Mhh, good point. I'll add it there.

**Pull request merged**
